services:
  web:
    build:
      context: .
      args:
        BUNDLE_INSTALL_ARGS: ""
        PNPM_INSTALL_ARGS: ""
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - pnpm_cache:/usr/local/pnpm
      - node_modules_cache:/usr/local/node_modules
    environment:
      MIDDLEMAN_LIVERELOAD_PORT: 4481
      MIDDLEMAN_LIVERELOAD_JS_HOST: 127.0.0.1
    ports:
      - "4480:4480"
      - "4481:4481"
volumes:
  bundle_cache:
  pnpm_cache:
  node_modules_cache:
